language: generic
sudo: required
services:
  - docker

before_script:
  # GCP Preparation
  - openssl aes-256-cbc -K $encrypted_3a4b98c9e056_key -iv $encrypted_3a4b98c9e056_iv -in service-account-full.json.enc -out service-account-full.json -d # give encrypted service account(permission) to travis
  - curl https://sdk.cloud.google.com > install.sh #download sdk
  - source install.sh --disable-prompts #install sdk silently
  - source $HOME/google-cloud-sdk/path.bash.inc #gcloud path
  - gcloud auth activate-service-account --key-file service-account-full.json #use auth for travis to acess compute engine
  - gcloud config set project "$PROJECT_ID" #set project id
  - gcloud config set compute/zone "$COMPUTE_ZONE" #set zone
  - gcloud config set compute/region "$COMPUTE_REGION" #set zone
  # AWS Preparation
  - openssl aes-256-cbc -K $encrypted_75afe9a5ecad_key -iv $encrypted_75afe9a5ecad_iv -in to-do-list-aws.pem.enc -out "$AWS_PEM" -d # get encrypted pem
  - chmod 400 ./"$AWS_PEM" # chmod 400 to pem
  - ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts # set known host, prevent interactive ssh
  # preparing image
  - npm install
  - npm run build
  - docker build -t "$DOCKER_USERNAME"/"$IMAGE" .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push "$DOCKER_USERNAME"/"$IMAGE"

script:
   # delete current docker-compose (aws)
  - ssh -i $AWS_PEM $AWS_HOST@$DEPLOY_HOST "rm -rf ./docker-compose.yml"
  - gcloud compute ssh $VM_NAME --command "rm -rf ./docker-compose.yml"

after_script:
  # scp new docker-compose
  - scp -i $AWS_PEM ./docker-compose.yml $AWS_HOST@$DEPLOY_HOST:$AWS_WORKDIR
  - gcloud compute scp ./docker-compose.yml $VM_NAME:$GCP_WORKDIR
  # deploy
  - ssh -i $AWS_PEM $AWS_HOST@$DEPLOY_HOST "bash -s" < deploy-aws.sh
  - gcloud compute ssh $VM_NAME --command "bash -s" < deploy-gcp.sh

# deploy:
#   provider: script
#   script: bash deploy.sh #gcp script
#   script: bash deploy-aws.sh #aws script
#   on:
#     branch: master
